
platform:ios,’7.0’
project 'shopForiOS.xcodeproj'

target :shopForiOS do
  pod 'CocoaAsyncSocket','~> 7.4.3'
  pod 'ProtocolBuffers', '~> 1.9.9.2'
  pod 'MSWeakTimer', '~> 1.1.0'
  pod 'RHSocketKit'
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'SDWebImage'
  pod 'ScreenCompatible_LFL', '~> 1.0.0'
  pod 'MBProgressHUD'
  pod 'SocketRocket', '~> 0.5.1'

end